### ISSUE TITLE
null is not an object (evaluating RNAWSCognito.computeModPow)

### ISSUE THREAD

**Issue by kirkryan** [aws-amplify/amplify-js#3682]
**Describe the bug**
I hope this saves someone some time (and frustration)

A user can sign up or view the login page, but upon login, the following error is observed:

**null is not an object (evaluating RNAWSCognito.computeModPow)**

**To Reproduce**
Create new >=RN0.60.0 project
cd ios
pod install
build

**Expected behavior**
Amplify podspec should correctly list RNAWSCognito.

**Smartphone (please complete the following information):**
 - All

**Additional context**
remember  **not** to use react-native link when working in >=0.60.0

**Fix**
simply run the following in your project root

```
yarn add amazon-cognito-identity-js
cd ios
pod install
```

**Comment by haverchuck** [comment]
@kirkryan - Thanks for posting this.  Can you post a little bit of detail on how you've configured your app?  Are you using the aws-amplify-react-native authenticator component?

**Comment by kirkryan** [comment]
@haverchuck - that’s correct. This is when using the withAuthenticator HOC on iOS builds.

**Comment by haverchuck** [comment]
@kirkryan  - Thanks.  I think this is an expected step, but we need to update our docs.

**Comment by BradyShober** [comment]
I have also run into this issue but when trying to use the recommended fix, I get a duplicate symbols Linker Error. In my app we are not using aws-amplify-react-native component. The specific error is 

> duplicate symbol _OBJC_CLASS_$_JKBigInteger in:
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/JKBigInteger2/libJKBigInteger2.a(JKBigInteger.o)
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/libRNAWSCognito.a(JKBigInteger.o)
duplicate symbol _OBJC_METACLASS_$_JKBigInteger in:
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/JKBigInteger2/libJKBigInteger2.a(JKBigInteger.o)
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/libRNAWSCognito.a(JKBigInteger.o)
duplicate symbol _OBJC_IVAR_$_JKBigInteger.m_value in:
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/JKBigInteger2/libJKBigInteger2.a(JKBigInteger.o)
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/libRNAWSCognito.a(JKBigInteger.o)
duplicate symbol _OBJC_IVAR_$_JKBigDecimal.bigInteger in:
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/JKBigInteger2/libJKBigInteger2.a(JKBigDecimal.o)
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/libRNAWSCognito.a(JKBigDecimal.o)
duplicate symbol _OBJC_CLASS_$_JKBigDecimal in:
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/JKBigInteger2/libJKBigInteger2.a(JKBigDecimal.o)
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/libRNAWSCognito.a(JKBigDecimal.o)
duplicate symbol _OBJC_METACLASS_$_JKBigDecimal in:
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/JKBigInteger2/libJKBigInteger2.a(JKBigDecimal.o)
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/libRNAWSCognito.a(JKBigDecimal.o)
duplicate symbol _OBJC_IVAR_$_JKBigDecimal.figure in:
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/JKBigInteger2/libJKBigInteger2.a(JKBigDecimal.o)
    /Users/brady/Library/Developer/Xcode/DerivedData/traduki-ekuctotjpfcwpphgyaufmdogypjm/Build/Products/Debug-iphonesimulator/libRNAWSCognito.a(JKBigDecimal.o)
ld: 7 duplicate symbols for architecture x86_64

**Comment by kirkryan** [comment]
Run react-native unlink <package name>. Maybe it’s being imported twice after doing a react-native link (stay away from doing this in RN >=0.60.0. Also check in Xcode that it’s not listed in your project root / libraries, if so remove the reference. Also, check your pod file to ensure it’s not listed twice.

**Comment by BradyShober** [comment]
It was not linked, not listed under libraries, and not listed at all in the pod file. libRNAWSCognito.a was listed under frameworks that I tried removing but that didn't help.

**Comment by kirkryan** [comment]
Did you remove it, then clean the build folder, then try to rebuild?

**Comment by BradyShober** [comment]
Yes I did clean before trying to rebuild.

**Comment by kirkryan** [comment]
I’ve just spotted that you mentioned it’s not in your pod file - that’s explains it. I had to manually add it:

  `#pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js'`

**Comment by haverchuck** [comment]
@kirkryan Does a simple `pod install` from your ios directory resolve this?

**Comment by kirkryan** [comment]
It does once you’ve added it to your pod file yeah!

**Comment by BradyShober** [comment]
It still is giving the same error after I added it and ran pod install and also cleaned before rebuilding

**Comment by BradyShober** [comment]
It seems my issue was with Xcode keeping old derived data, after clearing everything in DerivedData it built fine. Also I have it running fine without it in the podfile because autolinking is working fine.

**Comment by kirkryan** [comment]
@BradyShober - nice, I’ll add that to my ever growing list of tricks and fixes

**Comment by Ashish5591** [comment]
@BradyShober- glad you got it working! Just to confirm, you did not need to add it to your podfile, but running pod install from the ios directory is still a necessary step?

**Comment by BradyShober** [comment]
@Ashish5591 Correct, as long as you've updated successfully to RN 0.60 or higher and have `require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'` and `use_native_modules!` in your podfile autolinking should be working. You do still need to run pod install from the ios directory.

**Comment by sammartinez** [comment]
@kirkryan I ended up making a call out of this on our docs about this and the workaround. Please see the above PR that was merged. Closing issue as the workaround resolves this issue

**Comment by bangersandflash** [comment]
This fix works for me and I can successfully build the project in Xcode. I can also run the project on the simulator via Xcode but if I try to use **react-native run-ios** I get the duplicate symbols error that @BradyShober mentioned above. Any ideas?

**Comment by bangersandflash** [comment]
Thanks @BradyShober I've tried deleting the DerivedData contents and I'm still getting the same error. To be clear, I can build the Xcode project without any issues and run/debug it through Xcode.

I'm only seeing the compilation error when I try to run **react-native run-ios** from Terminal.

**Comment by claudioviola** [comment]
Same issue of @BradyShober 
Any solution?

**Comment by Luckygirlllll** [comment]
I have the same error both in Android and IOS, any updates regarding this error? ` "react-native": "0.59.10",`

**Comment by Luckygirlllll** [comment]
This steps, solved my problem: 

```
npm install amazon-cognito-identity-js
then adding pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js' in Podfile
cd ios
pod install
```

**Comment by Luckygirlllll** [comment]
However, I still have a problem with Android, I'm still getting an error there, 
react-native link amazon-cognito-identity-js didn't help

**Comment by Ashish5591** [comment]
@Luckygirlllll what version of react native are you using? Did you run react-native link, before it started working in iOS as well?

Either you have < 0.60 and need to use react-native link, but wont have to do pod install.

Or you have > 0.60 in which case there is [autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) enabled (do not do react-native link). In this case you need to do pod install for iOS and nothing for Android

**Comment by Luckygirlllll** [comment]
@Ashish5591 0.59.10, in I`OS` it started to work without `react-native link `

**Comment by jimbol** [comment]
@bangersandflash Did you ever get it working when running react-native run-ios **from Terminal**.

**Comment by nghabaoduy** [comment]
Anyone have this issue?

Downloading dependencies
Installing JKBigInteger2 (0.0.5)

[!] Error installing JKBigInteger2
[!] /usr/bin/git clone https://github.com/astruts/JKBigInteger.git /var/folders/4c/prj_vdcs0ln44y4sxdp_vp300000gp/T/d20191105-23642-e4nnc1 --template= --single-branch --depth 1 --branch 0.0.5

Cloning into '/var/folders/4c/prj_vdcs0ln44y4sxdp_vp300000gp/T/d20191105-23642-e4nnc1'...
fatal: unable to access 'https://github.com/astruts/JKBigInteger.git/': Failed to connect to 10.210.250.7 port 8080: Operation timed out

**Comment by janoist1** [comment]
I'm still having this issue even after adding pod manually as mentioned above.
@Luckygirlllll how did you manage to make it work on ios?

**Comment by Luckygirlllll** [comment]
@janoist1 Try to delete Derived data from Xcode and try once again, also check if there is any errors during pod install

**Comment by janoist1** [comment]
@Luckygirlllll thanks for being so quick with response!
`/Users/ist1/Library/Developer/Xcode/DerivedData` is empty.
There were no errors during `pod install`.

**Comment by Luckygirlllll** [comment]
@janoist1 Check whether or not linking is correct in your IOS project for aws-amplify

**Comment by janoist1** [comment]
@Luckygirlllll Ultimate fix for RN60+: `pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js'` must not be added to `Podfile` manually.

**Comment by geoseong** [comment]
I had same issues with the following dependencies,
```json
"dependencies": {
    "aws-amplify": "^2.2.0",
    "aws-amplify-react-native": "^2.2.3",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^2.0.0-alpha.22",
    "react-navigation": "^4.0.10"
}
```

### testing on Android Emulator
I just tried `$ yarn add amazon-cognito-identity-js`, and error disappeared.
- **package.json**
  - `"amazon-cognito-identity-js": "^3.2.1",`

### testing on iOS Simulator
got error first,
```bash
error Could not find the following native modules: RNAWSCognito, RNGestureHandler, RNReanimated, RNScreens. Did you forget to run "pod install" ?
```
so I tried and error disappeared
- `$ cd ios`
- `$ pod install`
```bash
Detected React Native module pods for RNAWSCognito, RNGestureHandler, RNReanimated, and RNScreens
Analyzing dependencies
Downloading dependencies
Installing JKBigInteger2 (0.0.5)
Installing RNAWSCognito (3.2.1)
Installing RNGestureHandler (1.5.2)
Installing RNReanimated (1.4.0)
Installing RNScreens (2.0.0-alpha.22)
Generating Pods project
Integrating client project
Pod installation complete! There are 32 dependencies from the Podfile and 31 total pods installed.
```

**Comment by adibas03** [comment]
Leaving this here for anyone who it might help.
Following the instruction on the `amazon-cognito-identity-js` package readme is sufficient.
https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js  
I was battling this for 3 days, full disclosure, it was my error.
The `react-native link` command did not work, because I changed the package name, and did not update the android activity folder hierarchy correctly, which is required for the linking to happen

**Comment by thenderson55** [comment]
Installing ```amazon-cognito-identity-js``` solves the issue but does your login persist?

I get logged out on every refresh. Some other older issues mention this and the solution was to upgrade from ```aws-amplify``` v1 to v2. I am now on v3 doesn't persist.

I will probably try ```redux persist``` but it seems like amplify should automatically access asyncStorage to persist login

**Comment by Jonathan0wh** [comment]
This should be added to README documentation of `aws-amplify`, especially for the React Native part.
I followed the normal README guide to install `aws-amplify` but also got this error before I googled it and went here.
It should be emphasised that both `aws-amplify` and `amazon-cognito-identity-js` should be installed for React Native.

**Comment by smartcris** [comment]
> This should be added to README documentation of `aws-amplify`, especially for the React Native part.
> I followed the normal README guide to install `aws-amplify` but also got this error before I googled it and went here.
> It should be emphasised that both `aws-amplify` and `amazon-cognito-identity-js` should be installed for React Native (at least for now as a workaround).

My yarn install log clearly show the amazon-cognito-identity-js being added when the "@aws-amplify/auth" package is installed. More than a clarification we need a fix.
