### PR TITLE
fix(@aws-amplify/core): bump tslib to ^2.1.0 to guarantee __spreadArray at runtime

### LINKED ISSUE #14879: @aws-amplify/core (v5) declares tslib ^1.8.0 but emits __spreadArray (latent __spreadArray-is-not-a-function risk)
### Summary

On the **v5 line** (`v5-stable`), **`@aws-amplify/core@5.8.18`** declares `"tslib": "^1.8.0"` but its emitted `lib/` calls **`tslib.__spreadArray`**, which only exists in **tslib ≥ 2.1.0**. `^1.8.0` means `>=1.8.0 <2.0.0`, so it can only ever resolve `tslib@1.x` — which does **not** export `__spreadArray`.

This is the **same class of bug** as #14865 (fixed for `@aws-amplify/datastore` in #14878): a package whose compiled output needs `tslib >= 2.1` but whose declared `tslib` range does not guarantee it, so a consumer can hit `__spreadArray is not a function` at bundle/runtime. core simply wasn't part of the #14865 regression, so it has gone unnoticed.

> Filing as a separate follow-up per review of #14878, which was intentionally kept datastore-only.

### Root cause

All v5 packages compile with `target: es5` + `downlevelIteration: true` + `importHelpers: true` (`packages/tsconfig.base.json`), so their emitted `lib/` **imports TypeScript helpers from `tslib`**. `__spreadArray` (the TS 4.2+ helper) is only present in **tslib ≥ 2.1.0**:

| tslib | `__spread` | `__spreadArray` |
|---|---|---|
| 1.14.1 (max of `^1.8.0`) | function | **undefined** |
| 2.0.3 | function | **undefined** |
| 2.1.0+ | function | **function** |

`@aws-amplify/core@5.8.18` emits `tslib.__spreadArray` in its published `lib/` (4 files) yet pins `tslib: ^1.8.0`. If a consumer's tree resolves core's `tslib` import to a `1.x` copy, core throws `__spreadArray is not a function` — identical to the datastore failure in #14865.

Note this is not a new regression: `core@5.8.17` (in the *working* `aws-amplify@5.3.35`) already emitted `__spreadArray` with the same `^1.8.0` pin. It is a **latent** inconsistency that happens to be masked in most trees (a modern `tslib@2.x` is usually hoisted and resolved), but it is not guaranteed and can crash under the same peer-dependency conditions described in #14865 (e.g. a peer such as `apollo-boost` pulling `tslib@1.x`).

### Scope — stale `^1.8.0` pins on `v5-stable`

The following v5 packages declare `tslib: ^1.8.0`:

| package (v5-stable) | pins tslib | currently emits `__spreadArray`? |
|---|---|---|
| `@aws-amplify/core` (5.8.18) | `^1.8.0` | **yes (4 files)** — active latent crash risk |
| `@aws-amplify/api` | `^1.8.0` | no (today) |
| `@aws-amplify/api-graphql` | `^1.8.0` | no (today) |
| `@aws-amplify/api-rest` | `^1.8.0` | no (today) |
| `@aws-amplify/auth` | `^1.8.0` | no (today) |
| `@aws-amplify/pubsub` | `^1.8.0` | no (today) |
| `@aws-amplify/cache` | `^1.8.0` | no (today) |

`core` is the one that currently emits `__spreadArray`, so it is the active risk. The others don't emit it *today*, but their `^1.8.0` pins are the same latent trap datastore fell into — a routine TypeScript-emit change (exactly what flipped datastore's `__spread` → `__spreadArray` between `4.7.24` and `4.7.26`) would break them the same way.

### Suggested fix

Bump `tslib` to **`^2.1.0`** (the version that introduced `__spreadArray`; `^2.0.0` is insufficient since `2.0.x` still lacks it) for `@aws-amplify/core` — and, for consistency/robustness, for the other stale `^1.8.0` pins (`api`, `api-graphql`, `api-rest`, `auth`, `pubsub`, `cache`). This matches the fix applied to datastore in #14878 and the `aws-amplify` meta-package, which already depends on `tslib ^2.0.0`.

### Related

- Same class as #14865 (datastore `__spreadArray is not a function`)
- Fixed for datastore in #14878

### PR DESCRIPTION
**Pull request by dikshit-n**
## Summary
Bump `@aws-amplify/core` v5 runtime `tslib` dependency from `^1.8.0` to `^2.1.0` so the emitted `__spreadArray` helper is guaranteed to exist at runtime.

## Problem
`@aws-amplify/core@5.8.18` compiles with `importHelpers: true` + `target: es5`, emitting calls to `tslib.__spreadArray`. However, `^1.8.0` resolves only to `tslib@1.x` (max `1.14.1`), which does **not** export `__spreadArray` — it was added in `tslib@2.1.0`. Under certain dependency-tree conditions (e.g. a peer pulling `tslib@1.x`), this causes `__spreadArray is not a function` at runtime.

This is the same class of bug fixed for `@aws-amplify/datastore` in #14878.

## Solution
Bump `dependencies.tslib` from `^1.8.0` to `^2.1.0` in `packages/core/package.json`. This mirrors the datastore fix and guarantees the `__spreadArray` helper is available when core's lib is consumed.

## Changes Made
- `packages/core/package.json`: `tslib` dependency range `^1.8.0` → `^2.1.0`

## Testing
- No code changes — dependency version bump only.
- `npm ls tslib` in `@aws-amplify/core` workspace confirms `^2.1.0` resolves correctly.

## Checklist
- [x] Dependency range is a non-breaking bump
- [x] Matches the pattern applied to `@aws-amplify/datastore` in #14878
- [x] No code changes — trivially safe fix
- [x] Targets `v5-stable` maintenance branch

Closes #14879

### CODE REVIEW

**Review by bobbor — APPROVED** [review]

**Comment by bobbor** [comment]
Thanks @dikshit-n for the PR. Looks good. let's move forward

**Review by osama-rizk — APPROVED** [review]

**Comment by dikshit-n** [comment]
Hi @aws-amplify/maintainers 👋

This PR (tslib version bump to ^2.1.0 for __spreadArray support) has been open for about 7 weeks with no recent activity. 

Is there anything I can do to help move this forward — additional context, tests, or changes? Happy to address any feedback or close if the timing isn't right.

Thanks!
