### ISSUE TITLE
Auth.changePassword TypeError: user.getSession is not a function

### ISSUE THREAD

**Issue by strykerCrew** [aws-amplify/amplify-js#2214]
**Describe the bug**
When upgrading library to 1.1.10 login and logout seems to work, however changing password shows a `Possible Unhandled Promise Rejection`

**To Reproduce**
```
Auth.currentAuthenticatedUser()
      .then((user) => {
        return Auth.changePassword(user, oldPassword, newPassword)
      })
      .then((data) => {
        console.log('changePassword:', data)
        this.props.navigation.navigate('Profile')
      })
      .catch((err) => {
        console.log(err)
      })
```
Generates:
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: user.getSession is not a function
TypeError: user.getSession is not a function
    at blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:103866:22
    at tryCallTwo (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:8841:7)
    at doResolve (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:9005:15)
    at new Promise (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:8864:5)
    at AuthClass.userSession (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:103864:20)
    at blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:103676:23
    at tryCallTwo (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:8841:7)
    at doResolve (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:9005:15)
    at new Promise (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:8864:5)
    at AuthClass.userAttributes (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:103675:20)
```

**Expected behavior**
I expect to change password per the documentation and not have any errors.

**Smartphone (please complete the following information):**
 - Device: iPhoneX Simulator

**Additional context**

- "react": "^16.3.1",
- "react-native": "^0.55.4",
- "aws-amplify": "^1.1.10"

**Comment by powerful23** [comment]
@strykerCrew hi can you provide more info like the `user` you got from `Auth.currentAuthenticatedUser()`. You can also check the debug info by `window.LOG_LEVEL='DEBUG'`

**Comment by strykerCrew** [comment]
```
[DEBUG] 16:40.65 AuthClass - Getting the session from this user:
:Object
aud: "..."
auth_time: 1543622644
cognito:username: "email@example.com"
email: "email@example.com"
email_verified: true
event_id: "..."
exp: 1543626244
iat: 1543622644
id: "..."
iss: "https://cognito-idp..."
sub: "..."
token_use: "id"
```

**Comment by powerful23** [comment]
@strykerCrew That's weird. The user object should be a CognitoUser Object. Also I noticed that the tracing stack you pasted: 
```TypeError: user.getSession is not a function
    at blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:103866:22
    at tryCallTwo (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:8841:7)
    at doResolve (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:9005:15)
    at new Promise (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:8864:5)
    at AuthClass.userSession (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:103864:20)
    at blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:103676:23
    at tryCallTwo (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:8841:7)
    at doResolve (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:9005:15)
    at new Promise (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:8864:5)
    at AuthClass.userAttributes (blob:file:///6134849c-a9bf-4aff-8573-9a29532aed54:103675:20)
```

Did you run `userAttributes` somewhere in your code? Or is it the full tracing stack? Maybe some other function is calling that. But as I know the `currentAuthenticatedUser` method doesn't call that function.

**Comment by strykerCrew** [comment]
@powerful23  We don't have `userAttributes` anywhere in our code. This seems to be generated when the code hits `return Auth.changePassword(user, oldPassword, newPassword)` as the example code above. 

This does work on `aws-amplify=1.0.0`, but breaks when we try to upgrade.

**Comment by strykerCrew** [comment]
@powerful23 in the `aws-amplify-react-native` it uses `Auth.completeNewPassword`, should we be using that instead of `Auth.changePassword`?

We do not use `aws-amplify-react-native` and I didn't see the `Auth.changePassword` in the code for that package. Is it deprecated?

**Comment by strykerCrew** [comment]
Ok, so you are using new versions of react and react native than listed?

**Comment by strykerCrew** [comment]
We are working on upgrading React to see if that fixes it.

**Comment by powerful23** [comment]
@strykerCrew hi please notice that the sample code above only works when the MFA is not required in the your Cognito User Pool(which means users can directly sign in).

**Comment by strykerCrew** [comment]
Yes, I saw that. I am working on putting our code in a sample app to see if I still have the issue.

**Comment by strykerCrew** [comment]
@manueliglesias thanks for the help, I was able to track it down by creating a new app with the latest React/React Native. It looks like the culprit comes from legacy code using the `Auth.signIn` followed by getting the user session followed by a `Auth.federatedSignIn` with Cognito. I simplified to `Auth.signIn` and then `Auth.currentCredentials`. 

Why would this not break on auth and only show in the password change?

**Comment by manueliglesias** [comment]
@strykerCrew We suspect that you might be calling `federatedSignIn` somewhere in your code and this is not needed in this case, because the library takes care of getting the credentials when you have an Identity Pool configured with a User Pool.

Could you confirm that's the case? If so, this would explain the problem; as roughly speaking, the `federatedSignIn` is an independent process which caches it's own user object which makes sense when running it independently. However if you use it along with the standard Auth methods that are already performing federation, problems occur. 

If this is the case could you let us know why you might have thought that calling this separately in your code was necessary? We haven't seen customers do this before.

**Comment by deepak-kundapur** [comment]
Please find the below code . It worked for me.

async changePassword() {
  var poolData = {
    UserPoolId: "Your pool Id",
    ClientId: "Your client Id"
  };
    var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData );
    var userData = {
      Username: "current logged in username here",
      Pool: userPool
    };
    var cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);
    var authenticationData = {
      Username: "current logged in username here",
      Password: "current password"
    };
    var authenticationDetails = new AmazonCognitoIdentity.AuthenticationDetails(authenticationData);
   return cognitoUser.authenticateUser(authenticationDetails, {
      onSuccess: function (session) {
        if (session) {
          return cognitoUser.changePassword( "current password",  "new password", async (err, result) => {
            if (err) {
              console.log("Change Password error is" + JSON.stringify(err) + err)
            }
            if (result) {
              if(JSON.stringify(result) == "SUCCESS"){
                Swal.fire({
                  title: "Success!",
                  text: "Your new password is updated successfully",
                  type: "success",
                })
              }
            }
          });
        }
      },
      onFailure: function (err) {
        console.log("authenticateUser() ERROR: " + err);
      }
    });
  }
