### ISSUE TITLE
Angular build fails with missing Node.js core modules from aws-amplify v6.15.10 onwards

### ISSUE THREAD

**Issue by shaheer-k** [aws-amplify/amplify-js#14782]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [x] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```

System:
    OS: Windows 11 10.0.26200
    Memory: 28.61 GB / 63.65 GB
  Binaries:
    Node: 22.14.0 
    npm: 11.2.0
  Browsers:
    Chrome: 147.0.7727.101
    Edge: Chromium (147.0.3912.60)
    Internet Explorer: 11.0.26100.8115
  npmPackages:
    @angular-builders/custom-webpack: ^21.0.0 => 21.0.3 
    @angular-eslint/template-parser: ^21.0.0 => 21.3.1 
    @angular/animations: ^21.2.0 => 21.2.5 
    @angular/build: ^21.2.0 => 21.2.3 
    @angular/cli: ^21.2.0 => 21.2.3 
    @angular/common: ^21.2.0 => 21.2.5 
    @angular/compiler: ^21.2.0 => 21.2.5 
    @angular/compiler-cli: ^21.2.0 => 21.2.5 
    @angular/core: ^21.2.0 => 21.2.5 
    @angular/elements: ^21.2.0 => 21.2.5 
    @angular/forms: ^21.2.0 => 21.2.5 
    @angular/localize: ^21.2.0 => 21.2.5 
    @angular/platform-browser: ^21.2.0 => 21.2.5 
    @angular/platform-browser-dynamic: ^21.2.0 => 21.2.5 
    @angular/pwa: ^21.2.0 => 21.2.3 
    @angular/router: ^21.2.0 => 21.2.5 
    @angular/service-worker: ^21.2.0 => 21.2.5 
    @cypress/angular:  0.0.0-development 
    @cypress/mount-utils:  0.0.0-development 
    @cypress/react:  0.0.0-development 
    @cypress/schematic: ^2.5.1 => 2.5.2 
    @cypress/svelte:  0.0.0-development 
    @cypress/vue:  0.0.0-development 
    @cypress/webpack-preprocessor: ^6.0.4 => 6.0.4 
    @datadog/browser-rum: ^6.30.1 => 6.31.0 
    @datadog/datadog-ci: ^5.9.1 => 5.9.1 
    @ngx-translate/core: ^15.0.0 => 15.0.0 
    @ngx-translate/http-loader: ^8.0.0 => 8.0.0 
    @types/jest: ^30.0.0 => 30.0.0 
    @types/node: 22.13.1 => 22.13.1 
    @types/sortablejs: ^1.15.3 => 1.15.9 
    @typescript-eslint/eslint-plugin: ^8.28.0 => 8.57.1 
    @typescript-eslint/parser: ^8.28.0 => 8.57.1 
    angular-eslint: ^21.0.0 => 21.3.1 
    aws-amplify: ^6.15.10 => 6.15.10 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/adapter-core/internals:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/internals:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/enable-oauth-listener:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/data:  undefined ()
    aws-amplify/data/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    cypress: 14.2.0 => 14.2.0 
    cypress-mochawesome-reporter: ^3.8.2 => 3.8.4 
    dotenv: ^16.4.7 => 16.6.1 
    eslint: ^9.23.0 => 9.39.4 
    eslint-config-prettier: ^10.1.1 => 10.1.8 
    eslint-plugin-cypress: ^4.2.0 => 4.3.0 
    eslint-plugin-jest: ^28.6.0 => 28.14.0 
    eslint-plugin-prettier: ^5.2.1 => 5.5.5 
    guid-typescript: 1.0.9 => 1.0.9 
    husky: ^9.1.7 => 9.1.7 
    jest: ^30.0.0 => 30.3.0 
    jest-environment-jsdom: ^30.3.0 => 30.3.0 
    jest-jasmine2: ^30.0.0 => 30.3.0 
    jest-junit: ^16.0.0 => 16.0.0 
    jest-preset-angular: ^16.1.1 => 16.1.1 
    keycloak-js: ^25.0.6 => 25.0.6 
    launchdarkly-js-client-sdk: ^3.5.0 => 3.9.0 
    lint-staged: ^15.2.0 => 15.5.2 
    ngx-cookie-service: ^21.1.0 => 21.3.1 
    nxt-sortablejs: ^21.0.0 => 21.0.0 
    prettier: ^3.3.3 => 3.8.1 
    requirejs: ^2.3.7 => 2.3.8 
    rxjs: ~7.8.2 => 7.8.2 (6.6.7)
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/internal-compatibility:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    sortablejs: ^1.15.6 => 1.15.7 
    swiper: ^12.1.2 => 12.1.2 
    test-project:  1.0.0 
    ts-loader: ^9.5.1 => 9.5.4 
    typescript: ~5.9.2 => 5.9.3 
    webpack: ^5.98.0 => 5.105.4 (5.105.2)
    zone.js: ~0.15.0 => 0.15.1 
  npmGlobalPackages:
    @angular/cli: 19.2.7
    aws-cdk: 2.1112.0
    npm: 11.2.0

```

</details>

### Describe the bug

After upgrading aws-amplify from 6.15.9 to 6.15.10 (and above), Angular builds fail with errors about missing Node.js core modules such as http2 and node:stream. The error does not occur with 6.15.9.

Error: node_modules/@aws-sdk/types/node_modules/@smithy/types/dist-types/http/httpHandlerInitialization.d.ts:1:69 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

1 import type { Agent as hAgent, AgentOptions as hAgentOptions } from "http";
                                                                      ~~~~~~


Error: node_modules/@aws-sdk/types/node_modules/@smithy/types/dist-types/http/httpHandlerInitialization.d.ts:2:71 - error TS2307: Cannot find module 'https' or its corresponding type declarations.

2 import type { Agent as hsAgent, AgentOptions as hsAgentOptions } from "https";
                                                                        ~~~~~~~

Error: node_modules/@aws-sdk/types/node_modules/@smithy/types/dist-types/streaming-payload/streaming-blob-common-types.d.ts:1:31 - error TS2307: Cannot find module 'stream' or its corresponding type declarations.

1 import type { Readable } from "stream";
                                ~~~~~~~~


Error: node_modules/@aws-sdk/types/node_modules/@smithy/types/dist-types/streaming-payload/streaming-blob-payload-input-types.d.ts:1:31 - error TS2307: Cannot find module 'stream' or its corresponding type declarations.

1 import type { Readable } from "stream";



### Expected behavior

Upgrading from 6.15.9 to 6.15.10+ should not introduce build errors related to missing Node.js modules like http2 or node:stream. 

### Reproduction steps

Use Angular (v21) with aws-amplify 6.15.10 or later.
Run ng build or ng serve.
See errors like:
Expected behavior
Angular builds should work out of the box in browser environments, as with aws-amplify 6.15.9 and earlier.

### Code Snippet

```javascript
// Put your code below this line.

```


### Log output

<details>

```
// Put your logs below this line


```

</details>


### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

**Comment by osama-rizk** [comment]
Hi @shaheer-k ,
 
Thank you for creating this issue. We will investigate and get back to you as soon as we have more information or need additional details.

**Comment by osama-rizk** [comment]
Hi @shaheer-k, thanks for reporting this — we've been able to reproduce the issue.

   We're working on a fix for this.

   In the meantime, you can work around it by setting skipLibCheck to true in your tsconfig.json:

```
   {
     "compilerOptions": {
       "skipLibCheck": true,
       ...
     },
       ...
   }

```

   This tells TypeScript to skip type-checking of .d.ts files in node_modules, which avoids the errors while
   having no impact on type-checking of your own code. This is also the default value Angular CLI generates for
   new projects.

   We'll update this issue once a proper fix is available.
