### ISSUE TITLE
awsmobile publish build problem - angular

### ISSUE THREAD

**Issue by jgmurray23** [aws-amplify/amplify-js#1472]
I have problem when attempting to publish an angular amplify project. I've built the project according to this page: https://aws-amplify.github.io/amplify-js/media/angular_guide

and the project, deployed locally with awsmobile run works perfectly ( ng build works fine )  However, when I attempt to publish it to s3/cloudfront (awsmobile publish and or ng build --prod ), it fails with the following errors:

ERROR in node_modules/@ionic/core/dist/types/components.d.ts(248,46): error TS2315: Type 'CustomEvent' is not generic.
node_modules/@ionic/core/dist/types/components.d.ts(252,43): error TS2315: Type 'CustomEvent' is not generic.
.
.
.
I'm not doing anything fancy, just the base project almost verbatim. 

awsmobile -V 

1.1.5

ng -v 

Angular CLI: 1.6.8
Node: 8.11.4
OS: darwin x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

I don't understand why it only complains with the production build. I suspect an version mismatch with angular and/or ionic somewhere - but my efforts to figure out have failed.

**Comment by jgmurray23** [comment]
OK, it won't build with typescript less then 2.7.0 and I think this is the reason:

https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#customevent-is-now-a-generic-type

I bumped typescript to 2.7.0 in package.json
then I ran npm install 
now ng build --prod works as well as awsmobile publish
However, the angular-cli compiler complains:
@angular/compiler-cli@5.2.11 requires typescript@'>=2.4.2 <2.7.0' but 2.7.2 was found instead.

but so far I don't see any negative effects. I wonder if perhaps there might be further dependency problems, but so far so good.

**Comment by haverchuck** [comment]
@jgmurray23  We have updated aws-amplify-angular so that it no longer uses Ionic as a dependency... so this error should now be addressed without manipulating typescript versions.  I'm closing the issue but feel free to reopen if the latest build doesn't fix your problem.  

Thanks!
