### ISSUE TITLE
TypeError: form.requestSubmit is not a function

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-js#5325]
**Describe the bug**

Introduced in ce74563b427cb2713ad0f1a778441b8f1f3f3ac5, `form.requestSubmit` does not work in Firefox (current version is **68**):

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit (Will land in _future_ Firefox **75**)
- https://www.stefanjudis.com/today-i-learned/requestsubmit-offers-a-way-to-validate-a-form-before-submitting-it/#a-new-method-that-does-what-developers-expect

**To Reproduce**

1. Add `<amplify-authenticator />` to an app.
2. Click "Sign In"
3. See error:

    > <img width="1034" alt="Screen Shot 2020-04-07 at 5 11 26 PM" src="https://user-images.githubusercontent.com/15182/78730943-1b61c600-78f3-11ea-90fd-b4fa5ed7b372.png">

**Expected behavior**

Complete sign in.

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 104.03 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 68.6.0
    Safari: 13.1
  npmPackages:
    @aws-amplify/ui-react: unstable => 0.2.1
    @types/node: ^13.9.1 => 13.11.0
    @types/react: ^16.9.23 => 16.9.32
    aws-amplify: unstable => 3.0.7-unstable.3+bb17bcb83
    next: latest => 9.3.4
    react: latest => 16.13.1
    react-dom: latest => 16.13.1
    typescript: ^3.8.3 => 3.8.3
  npmGlobalPackages:
    @aws-amplify/cli: 4.13.3
    create-react-app: 3.1.1
    npm: 6.9.0
    pure-prompt: 1.10.3
```

</details>

**Additional context**

I'm running https://github.com/aws-amplify/amplify-js/pull/5324, but that should be unrelated.

**Comment by ericclemmons** [comment]
Fixed via #5333
