### ISSUE TITLE
Version 4.2.9 of library causing “module build failed” with error “api.assumption is not a function”

### ISSUE THREAD

**Issue by acusti** [aws-amplify/amplify-js#8878]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, Storage

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 122.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.21.0 - /opt/homebrew/bin/npm
    Watchman: 2021.08.30.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 92.1.28.105
    Chrome: 93.0.4577.63
    Chrome Canary: 94.0.4604.0
    Firefox Developer Edition: 92.0
    Safari: 14.1.2
  npmPackages:
    @acusti/dropdown: ^0.11.0 => 0.11.0
    @acusti/input-text: ^0.4.0 => 0.4.0
    @acusti/textual: ^0.1.0 => 0.1.0
    @aws-sdk/client-dynamodb: ^3.31.0 => 3.31.0
    @aws-sdk/lib-dynamodb: ^3.31.0 => 3.31.0
    @size-limit/preset-app: ^5.0.3 => 5.0.3
    @testing-library/jest-dom: ^5.11.4 => 5.14.1
    @testing-library/react: ^11.1.0 => 11.2.7
    @types/jest: ^26.0.15 => 26.0.24 (27.0.1)
    @types/node: ^12.0.0 => 12.20.24 (16.9.1)
    @types/react: ^17.0.0 => 17.0.20
    @types/react-dom: ^17.0.0 => 17.0.9
    amazon-cognito-identity-js: ^5.1.0 => 5.1.0
    aws-amplify: ^4.2.9 => 4.2.9
    classnames: ^2.3.1 => 2.3.1
    history: ^5.0.1 => 5.0.1
    jotai: https://pkg.csb.dev/pmndrs/jotai/commit/d8ea2e48/jotai => 1.3.2
    prettier: ^2.3.2 => 2.4.0
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-router-dom: ^6.0.0-beta.2 => 6.0.0-beta.4
    react-scripts: 4.0.3 => 4.0.3
    sass: ^1.37.5 => 1.39.2
    size-limit: ^5.0.3 => 5.0.3
    slugify: ^1.6.0 => 1.6.0
    typescript: ^4.1.2 => 4.4.3
    web-vitals: ^1.0.1 => 1.1.2
  npmGlobalPackages:
    npm: 7.21.0
```

</details>

### Describe the bug

after upgrading aws-amplify from v4.2.4 → v4.2.9, running `yarn start` in a CRA bootstrapped react app produces the following output:
```
yarn run v1.22.11
$ react-scripts start
ℹ ｢wds｣: Project is running at http://192.168.1.63/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/andrew/Projects/tributary/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...
Failed to compile.

./node_modules/@aws-amplify/auth/lib-esm/Auth.js
TypeError: [BABEL] /<redacted>/node_modules/@aws-amplify/auth/lib-esm/Auth.js: api.assumption is not a function (While processing: "/<redacted>/node_modules/babel-preset-react-app/dependencies.js$0$2")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
```

### Expected behavior

i expected the project to continue to build successfully

### Reproduction steps

1. with an existing react app (bootstrapped with create-react-app + react-scripts v4.0.3), i upgraded from aws-amplify v4.2.4 → v4.2.9 and installed `@aws-sdk/client-dynamodb` and `@aws-sdk/lib-dynamodb`, both v3.31.0
2. i ran `yarn start`, resulting in the `api.assumption is not a function` error

### Log output

<details>

```
// Put your logs below this line
yarn run v1.22.11
$ react-scripts start
ℹ ｢wds｣: Project is running at http://192.168.1.63/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/andrew/Projects/tributary/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...
Failed to compile.

./node_modules/@aws-amplify/auth/lib-esm/Auth.js
TypeError: [BABEL] /<redacted>/node_modules/@aws-amplify/auth/lib-esm/Auth.js: api.assumption is not a function (While processing: "/<redacted>/node_modules/babel-preset-react-app/dependencies.js$0$2")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
```

</details>

### Manual configuration

```js
Amplify.configure({
    Auth: {
        // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
        identityPoolId: 'us-east-1:xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',

        // REQUIRED - Amazon Cognito Region
        region: 'us-east-1',

        // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: 'us-east-1_XXXXXXXXX',

        // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',

        // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
        mandatorySignIn: false,
    },

    Storage: {
        AWSS3: {
            // REQUIRED -  Amazon S3 bucket name
            bucket: 'name-of-my-s3-bucket',
            // OPTIONAL -  Amazon service region
            region: 'us-east-1',
        },
    },
});
```

**Comment by acusti** [comment]
i did some more testing with different versions and it seems to actually be a babel issue. i had just upgraded aws-amplify and the error pointed at `node_modules/@aws-amplify/auth/lib-esm/Auth.js`, but looks like that was a coincidence, because when i reverted my babel version and maintained aws-amplify@4.2.9, the project works again. sorry for the noise!

**Comment by acusti** [comment]
seems like it might be the same as https://github.com/aws-amplify/amplify-js/issues/8878
